//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineBotAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3rB6XGDoWogSsn6F+p3myIcK4Wlb5fpLLbKDNRDSvc6FO1jGu3iNugzk+7UU2n642qCrNVksrdyOP8ywi" +
            "fsd6e4NX8g18rdm3MaswdKrfzRZRU0nxUfDi+1z/lwZhctNgaRHfNNQRO/aNKCsXM65OwdB04t89/1O/" +
            "w1cDnyilFU=")]
        public string ChannelAccessToken {
            get {
                return ((string)(this["ChannelAccessToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://localhost:27017/Windom")]
        public string MongoServerSettings {
            get {
                return ((string)(this["MongoServerSettings"]));
            }
        }
    }
}
